### DISCUSSION TITLE
`worker` logs a `Maybe you forgot to import it?` when it receives a message from the queue

### DISCUSSION THREAD

**Discussion by devraj** [taskiq-python/taskiq#113] [Q&A] [answered]
I have spotted this before and have managed to resolve and am back at seeing the same message being emitted by the worker. I am running the application (FastAPI based, all [source code available here](https://github.com/anomaly/lab-python-server)).

The worker is kicker off inside a container:
```yaml
  # TaskIQ worker
  worker:
    container_name: ${PROJ_NAME}-worker
    build:
      context: .
      dockerfile: Dockerfile
    command: ["taskiq", "worker", "${PROJ_NAME}.broker:broker"]
    env_file:
      - .env.development
    restart: unless-stopped
    volumes:
      - ./src/${PROJ_NAME}:/opt/${PROJ_NAME}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
```

The broker is defined as per the examples and uses `RabbitMQ` and `redis`:
```python
from .config import config

# See PyPI for more information about taskiq_redis
# https://pypi.org/project/taskiq-redis/
# 
# Redis is recommended as the results backend for the tasks
from taskiq_redis import RedisAsyncResultBackend

# RabbitMQ is recommended as the broker 
from taskiq_aio_pika import AioPikaBroker

redis_result_backend = RedisAsyncResultBackend(
    config.redis_dsn
)

broker = AioPikaBroker(
    config.amqp_dsn,
    result_backend=redis_result_backend
)
```

The `FastAPI` application in `api.py` definitely calls the `startup` and `shutdown` on the events:

```python
# TaskIQ configurartion so we can share FastAPI dependencies in tasks
@app.on_event("startup")
async def app_startup():
    if not broker.is_worker_process:
        await broker.startup()

# On shutdown, we need to shutdown the broker
@app.on_event("shutdown")
async def app_shutdown():
    if not broker.is_worker_process:
        await broker.shutdown()
```

For the purposes of getting things working I have `tasks` defined [here](https://github.com/anomaly/lab-python-server/blob/main/src/labs/routers/auth/tasks.py) and a `FastAPI` [endpoint](https://github.com/anomaly/lab-python-server/blob/main/src/labs/routers/auth/create.py) kicks off the task.

Extract from `tasks.py`:
```python
from sqlalchemy.ext.asyncio import AsyncSession
from taskiq import TaskiqDepends

from ...db import get_async_session
from ...broker import broker

@broker.task
async def send_account_verification_email(
    session: AsyncSession = TaskiqDepends(get_async_session)
) -> None:
    import logging
    logging.error("Kicking off send_account_verification_email")
```

Extract from `create.py ` that kicks off the task.:
```python
@router.get("/verify")
async def verify_user(request: Request):
    """Verify an account
    """
    await send_account_verification_email.kiq()
    return {"message": "hello world"}
```

When I kick off the events, the handler returns as expected, but the worker logs a message saying:
```
labs-worker         | [2023-04-26 00:22:30,824][taskiq.receiver.receiver][WARNING][worker-1] task "labs.routers.auth.tasks:send_account_verification_email" is not found. Maybe you forgot to import it?
```

I know I had this working at some point and obviously am missing something that is causing it to not work again. I thought I'd reach out here to see if anyone can point my error.

Appreciate you sparing your time.
