### DISCUSSION TITLE
If there is no operation for a period of time, it is found that there is a warning that the amqp connection was stuck

### DISCUSSION THREAD

**Discussion by lpdswing** [taskiq-python/taskiq#194] [Q&A]
the warning log

`aiormq.connection:__reader:668 - Server connection <Connection: "amqp://guest:******@127.0.0.1:5672/" at 0x1152a6ee0> was stuck. No frames were received in 183 seconds.`

the rabbitmq log
```
tmp-rmq-1  | 2023-08-23 05:52:17.781108+00:00 [info] <0.15691.1> accepting AMQP connection <0.15691.1> (172.24.0.1:36618 -> 172.24.0.3:5672)                │tmp-kafka-1  | [2023-08-23 02:47:54,963] INFO [SnapshotEmitter id=0] Successfully
tmp-rmq-1  | 2023-08-23 05:52:18.335742+00:00 [info] <0.15691.1> connection <0.15691.1> (172.24.0.1:36618 -> 172.24.0.3:5672): user 'guest' authenticated an│ wrote snapshot 00000000000000100536-0000000001 (org.apache.kafka.image.publisher
d granted access to vhost '/'                                                                                                                               │.SnapshotEmitter)
tmp-rmq-1  | 2023-08-23 05:56:25.725122+00:00 [error] <0.15486.1> closing AMQP connection <0.15486.1> (172.24.0.1:32788 -> 172.24.0.3:5672):                │tmp-kafka-1  | [2023-08-23 03:47:50,990] INFO [SnapshotGenerator id=0] Creating n
tmp-rmq-1  | 2023-08-23 05:56:25.725122+00:00 [error] <0.15486.1> missed heartbeats from client, timeout: 60s                                               │ew KRaft snapshot file snapshot 00000000000000107728-0000000001 because we have w
tmp-rmq-1  | 2023-08-23 05:57:14.746616+00:00 [error] <0.15553.1> closing AMQP connection <0.15553.1> (172.24.0.1:46128 -> 172.24.0.3:5672):                │aited at least 60 minute(s). (org.apache.kafka.image.publisher.SnapshotGenerator)
tmp-rmq-1  | 2023-08-23 05:57:14.746616+00:00 [error] <0.15553.1> missed heartbeats from client, timeout: 60s                                               │tmp-kafka-1  | [2023-08-23 03:47:51,015] INFO [SnapshotEmitter id=0] Successfully
tmp-rmq-1  | 2023-08-23 05:58:02.029089+00:00 [error] <0.15624.1> closing AMQP connection <0.15624.1> (172.24.0.1:42672 -> 172.24.0.3:5672):                │ wrote snapshot 00000000000000107728-0000000001 (org.apache.kafka.image.publisher
tmp-rmq-1  | 2023-08-23 05:58:02.029089+00:00 [error] <0.15624.1> missed heartbeats from client, timeout: 60s
```
the rabbitmq docker-compose
```yml
version: "3.9"
services:
  rmq:
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    healthcheck:
      test: rabbitmq-diagnostics check_running -q
      interval: 3s
      timeout: 3s
      retries: 50
```
