### ISSUE TITLE
Docker Compose Example for Taskiq Integration with Redis, Flower, Worker, and Periodic Tasks

### ISSUE THREAD

**Issue by vahidzhe** [taskiq-python/taskiq#420]
I'm currently working on a project where I want to deploy Taskiq using Docker Compose. I would appreciate it if you could provide an example or further documentation on integrating Taskiq in a Docker environment that covers the following components:

Redis: Using a Redis container as the Taskiq broker.
Worker: Running Taskiq workers in a container.
Monitoring: Integrating a monitoring solution (similar to Flower in Celery) to monitor task execution.
Periodic Tasks: Setting up periodic tasks management within the Docker setup.
Having a unified Docker Compose example that covers these aspects would be extremely helpful for those of us looking to adopt Taskiq in a production environment.

**Comment by s3rius** [comment]
You can take a look at our examples repo. 

https://github.com/taskiq-python/examples/tree/master/fastapi-app

Although, currently monitoring using flower is not considered. But you can use https://github.com/spikeninja/taskiq-admin or use Prometheus middlewares.

**Comment by vahidzhe** [comment]
I tried both but neither of them worked.

**Comment by vahidzhe** [comment]
![Image](https://github.com/user-attachments/assets/c5070c7f-bb69-49bd-a102-23644054f35b)

A message is written that the task has started executing, but no information is displayed about the completion of execution.

docker-compose.yml

```
worker:
  build: .
  command: taskiq worker --log-level=INFO app.taskiq:broker
  depends_on:
  - redis
  volumes:
  - ./:/app

scheduler:
  build: .
  command: taskiq scheduler --log-level=INFO app.taskiq:scheduler
  depends_on:
  - redis
  volumes:
  - ./:/app
```
