### ISSUE TITLE
How use taskiq with fastapi and docker compose

### ISSUE THREAD

**Issue by rylofu** [taskiq-python/taskiq#462]
Help me understand how to use TaskIQ. I have a complex FastAPI application with tasks and periodic tasks. Am I correct in understanding the logic that in:
```
def create_lifespan():
    @asynccontextmanager
    async def lifespan(app: FastAPI):
        if not broker.is_worker_process:
            await broker.startup()
        yield
        if not broker.is_worker_process:
            await broker.shutdown()

    return lifespan
```

I start the broker only to push messages, not to process them? And to process them, I need to run a separate worker in Docker Compose like this:

```
nats:
  container_name: "nats"
  image: nats:2.11
  command: -js
  ports:
    - "4222:4222"
    - "8222:8222"
  volumes:
    - ./nats-data:/data
  networks:
    - my_network

worker:
  build: .
  command: pdm run taskiq worker app.config_data.tasks_queue.tasks_queue:broker -tp **/tasks.py
  networks:
    - my_network
  environment:
    NATS_URL: nats://nats:4222
```

In this setup, when starting the broker in the lifespan, I get the error:
```
nats.js.errors.BadRequestError: nats: BadRequestError: code=400 err_code=10013 description='consumer name already in use
```

Is this some kind of bug or am I doing something wrong?
